# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_driver', models.CharField(default='', max_length=100)),
                ('id_driver', models.IntegerField(default=0)),
                ('date_driver', models.DateTimeField(verbose_name='date published')),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CabUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(default='', max_length=100)),
                ('id_user', models.IntegerField(default=0)),
                ('date_user', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='cabdriver',
            name='cab_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_your_cab.CabUser'),
        ),
    ]
