# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_your_cab', '0002_remove_cabdriver_date_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabuser',
            name='date_user',
        ),
    ]
