# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_your_cab', '0005_remove_cabdriver_id_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabuser',
            old_name='id_user',
            new_name='password_user',
        ),
    ]
