# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_your_cab', '0007_driverhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverhistory',
            name='driv_point',
            field=models.IntegerField(default=0),
        ),
    ]
