# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_your_cab', '0008_driverhistory_driv_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverhistory',
            name='driv_point',
            field=models.FloatField(default=0),
        ),
    ]
