# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_your_cab', '0009_auto_20170423_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverhistory',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
